"""Assemble an UNBUILT `.dx`/`.unr` from a T3D trunk -- every authored actor with REAL brush polys,
no CSG, no lighting -- for the editor to `MAP LOAD` and build (`MAP REBUILD`/`LIGHT APPLY`/`PATHS
BUILD`), then `MAP SAVE`.

Why this shape. Driving the build with console verbs loses things the console cannot express:
`EDIT PASTE` GPFs building the brush model of complex retail geometry (`02_NYC_Warehouse`), there is
no verb to set a mover's keyframes, and none for `PrePivot`. If instead we WRITE the package
ourselves and let the editor only *build* it, every authored value is our bytes and none of those
verbs are needed.

The one thing that has to hold: a brush that arrives via `MAP LOAD` must participate in CSG.
`MAP IMPORTADD` brushes do not, and a save/reload of one does not repair it -- the add path prepares
something T3D does not carry. The prime suspect is the brush's own `Polys`: `assemble._brush_body`
writes a CSG brush's shape UModel with an EMPTY poly array; here we write the REAL ones so
`MAP LOAD` + `MAP REBUILD` carves.

It reuses `assemble.py`'s low-level helpers rather than `assemble_level`, which emits no brush polys.
"""
from __future__ import annotations

import re
from pathlib import Path

from uedcli.native import actor_write as AW
from uedcli.native import assemble as ASM
from uedcli.native import umodel as UM
from uedcli.native.actor_write import FPoly, Prop
from uedcli.native.props import ImportRef
from uedcli.native.level_write import URL, write_level_body
from uedcli.native.materialize import (_trunk_to_actorspecs, _pointregion_prop,
                                        _model_point_region)


def substrate_schema(*pkg_dirs: str | None):
    """An `ImportSchema` over the `.u` files in each dir (class schema + struct member layouts +
    defaults), for full typed-property serialization. Without a real schema every prop is dropped as
    untyped -- including `CsgOper`, which would leave a brush that carves nothing -- so this is not
    optional. Earlier dirs win, so the substrate's engine classes shadow a game copy of the same
    package."""
    from uedcli import mapimport
    paths: dict[str, str] = {}
    for d in (x for x in pkg_dirs if x):
        for f in Path(d).glob("*.u"):
            paths.setdefault(f.stem.casefold(), str(f))
    return mapimport.ImportSchema(resolver=lambda pkg: paths.get(pkg.casefold()))


class DegeneratePoly(ValueError):
    """A polygon the editor would silently discard, leaving a hole in the level."""


# An intra-level nav/zone ref (`PathNode'<pkg>.PathNode12'`, ...) -> its package qualifier, which for
# a trunk imported from a shipped map is the level's OWN package name. The probe that finds that name,
# for `rewrite_self_package_refs` and for `apply._level_referenced_packages` (which must not preload
# the level's own package as a dependency).
NAV_SELF_REF = re.compile(r"'([A-Za-z0-9_]+)\.(?:PathNode|PatrolPoint|HidePoint|ZoneInfo|LevelInfo)\d")


def _to_mylevel(value: str, self_pkgs: set[str]) -> str:
    for pkg in self_pkgs:
        value = value.replace(f"{pkg}.", "MyLevel.")
    return value


def rewrite_self_package_refs(level) -> None:
    """Requalify the level's OWN package refs to `MyLevel.`, IN PLACE.

    A trunk imported from a shipped map keeps its intra-level refs (`previousPath`, `FootRegion.Zone`,
    `Paths`, `Target`, ...) qualified with the ORIGINAL map's package name. Assembly counts a ref as
    internal only when it reads `MyLevel.` (`_internal_ref`); anything else becomes a package IMPORT,
    which the engine refuses -- `Can't import private object Teleporter 03_NYC_UNATCOHQ.Teleporter0`
    -> `Failed to load 'Level None.MyLevel'`. The load then aborts and (via `MAP LOAD`) silently saves
    an EMPTY map. `EDIT PASTE` tolerated these refs; `MAP LOAD` and the game do not.

    Detect the package from a nav/zone ref, then rewrite every occurrence of it. Those refs are build
    output (regenerated by `PATHS BUILD`/on load), so this does not change the built result."""
    self_pkgs = {m for a in level.actors.values() for _k, v in a.props
                 for m in NAV_SELF_REF.findall(v)}
    self_pkgs.discard("MyLevel")
    if not self_pkgs:
        return
    # Every place the package name can appear, matching what the T3D-text rewrite this replaced
    # reached: prop values, poly textures, and the actor's own class. EXCEPTION: an authored
    # PointRegion prop (FootRegion/HeadRegion/Region) whose Zone carries the level's own ORIGINAL
    # package qualifier is what the EDITOR fails to resolve at import (the session's level is
    # `MyLevel`), resetting the whole struct to spawn state -- byte-measured on the OceanLab
    # golden (`Zone=WaterZone'14_OceanLab_Lab.WaterZone0'` -> `(None,-1,0)`, 16/16; every
    # `MyLevel.`-qualified ref kept, 20/20). Reproduce the reset, don't rescue the ref.
    def _prop_value(k: str, v: str) -> str:
        if (k.split("(")[0].casefold() in ("footregion", "headregion", "region")
                and any(f"{pkg}." in v for pkg in self_pkgs)):
            return "(Zone=None,iLeaf=-1,ZoneNumber=0)"
        return _to_mylevel(v, self_pkgs)

    for a in level.actors.values():
        a.props = [(k, _prop_value(k, v)) for k, v in a.props]
        if a.cls:
            a.cls = _to_mylevel(a.cls, self_pkgs)
        for p in (a.brush.polys if a.brush is not None else ()):
            if p.texture:
                p.texture = _to_mylevel(p.texture, self_pkgs)


def _internal_ref(prop, present: set[str], owner: str, warnings: list):
    """Rewrite an intra-level object ref into an EXPORT ref, not a package import.

    A `MAP EXPORT` writes links between actors as `LevelInfo'MyLevel.LevelInfo0'`, `Base=`,
    `Target=` ... Left as-is, the assembler resolves `MyLevel.X` as an import of a package called
    `MyLevel`, and the engine refuses the load: `Can't import private object`. The target is in this
    very package, so it is an `ObjRef` -- resolved by name at body-build time. Recurses into a
    struct/array value so an internal ref INSIDE one (e.g. a struct member pointing at another actor)
    is rewritten too -- else it leaks a bogus `MyLevel` package import that silently empties the load."""
    prop.value = _rewrite_internal(prop.value, present, owner, prop.name, warnings)
    return prop


def _rewrite_internal(value, present: set[str], owner: str, where: str, warnings: list):
    if isinstance(value, ImportRef) and value.qualified.casefold().startswith("mylevel."):
        target = value.qualified.split(".", 1)[1]
        if target not in present:
            warnings.append(f"{owner}.{where}: refers to {value.qualified}, which this level does "
                            f"not contain -- dropped")
            return 0
        return ASM.ObjRef(target)
    if isinstance(value, AW.StructValue):
        for m in value.members:
            m.value = _rewrite_internal(m.value, present, owner, f"{where}.{m.name}", warnings)
    elif isinstance(value, AW.ArrayValue):
        for e in value.elements:
            e.value = _rewrite_internal(e.value, present, owner, where, warnings)
    return value


# A surface is not always a plain `Texture`: `02_NYC_Bar` binds `drtywater_a` as a `Fire.WetTexture`
# and `09_NYC_ShipFan` binds `Virus_SFX` as a `FireTexture`. Import one under the wrong class and the
# engine does not bind it -- the face ships untextured, with nothing in the log.
_TEXTURE_KINDS = ("Texture", "WetTexture", "WaterTexture", "FireTexture", "IceTexture",
                  "ScriptedTexture", "FractalTexture")


def _texture_kind_index(pkg_dirs) -> dict:
    """`(package stem, object name) -> the object's real class`, over the same `.utx` scan
    `build_texture_group_index` does (which returns only the group)."""
    from uedcli.native.pkg_write import parse_package
    out = {}
    for d in pkg_dirs or ():
        for utx in sorted(Path(d).glob("*.utx")):
            try:
                p = parse_package(utx.read_bytes())
            except Exception:
                continue
            for i, e in enumerate(p.exports):
                kind = p.class_of_export(i)
                if kind in _TEXTURE_KINDS:
                    out.setdefault((utx.stem.casefold(), p.names[e["nm"]].casefold()), kind)
    return out


def _texture_names(level) -> set[str]:
    """Every texture a level's brush polys name."""
    return {p.texture for a in level.actors.values() if getattr(a, "brush", None)
            for p in a.brush.polys if p.texture and p.texture.casefold() != "none"}


def _fpolys(brush, texture_ref=None, *, actor: str = "?") -> list[FPoly]:
    """Trunk `Polygon`s -> `FPoly`s, in the brush's own LOCAL space (the editor transforms by the
    actor's Location/Rotation/scale at build time, exactly as it does for a brush it built).

    `texture_ref(name) -> int` resolves a poly's stored `Package.Name` texture to an import ref.
    Without it every poly comes out untextured.

    The editor runs the `bspValidateBrush` LINK phase on an imported content brush's own shape model
    too (`_assign_content_ilinks`): coplanar same-facing same-texture faces fuse to a group master,
    every other poly keeps `iLink=-1`. A 6-face cube has no coplanar pair -> all -1, which is why
    every N<16 content brush matched before this was added (a cube can't tell "no link phase" from
    "link phase, no groups"). `Brush1643`'s two coplanar `Side` walls (WanChai N=16) are the first
    brush with real groups. A MOVER's iLinks are OVERWRITTEN by `build_mover_shape_model` downstream,
    so this assignment only reaches static brushes."""
    for i, p in enumerate(brush.polys):
        # The T3D importer drops a <3-vertex face without a word -- the level then ships with a hole
        # (measured: surfs 10 -> 9, nothing in the log). Catch it here, where we can name it.
        if len(p.vertices) < 3:
            raise DegeneratePoly(f"actor {actor!r} polygon {i} has {len(p.vertices)} vertices; "
                                 f"the editor would discard it and leave a hole")
    out = [FPoly(verts=[tuple(v) for v in p.vertices],
                 base=tuple(p.origin),
                 normal=(_calc_normal(p.vertices) or tuple(p.normal)),
                 texture_u=tuple(p.texture_u), texture_v=tuple(p.texture_v),
                 poly_flags=p.flags or 0, item=p.item,
                 texture_ref=(texture_ref(p.texture) if texture_ref and p.texture else 0),
                 # PanU/PanV serialize as u16; a real level's pans are signed and wrap, so mask
                 # rather than let struct.pack reject them.
                 pan_u=(p.pan or (0, 0))[0] & 0xFFFF, pan_v=(p.pan or (0, 0))[1] & 0xFFFF)
           for p in brush.polys]
    _assign_content_ilinks(out)
    return out


def _assign_ilinks(out: list[FPoly]) -> None:
    """The editor's import bspValidateBrush LINK phase (Editor.dll 0x37290; exact mirror of
    `bspcsg.rs::bsp_validate_brush_links`), IN PLACE on finalized-normal `FPoly`s: j links to i iff
    same texture object, EXACT TextureU/V, same PolyFlags, normal dot > 0.9999, and
    |N_i . (Base_j - Base_i)| in the +-0.001 coplanar band -- sequential 0..n-1 when nothing links."""
    nrm = [fp.normal for fp in out]                      # already the finalized (winding) normal
    for i, fp in enumerate(out):
        if fp.i_link != -1:
            continue
        fp.i_link = i
        for j in range(i + 1, len(out)):
            o = out[j]
            if o.i_link != -1 or o.texture_ref != fp.texture_ref:
                continue
            if o.texture_u != fp.texture_u or o.texture_v != fp.texture_v:
                continue
            if o.poly_flags != fp.poly_flags:
                continue
            # both predicates in the editor's f32 chain (x*x + y*y then + z*z, each op rounded)
            dot = _f32(_f32(_f32(nrm[i][0] * nrm[j][0]) + _f32(nrm[i][1] * nrm[j][1]))
                       + _f32(nrm[i][2] * nrm[j][2]))
            if dot <= _f32(0.9999):
                continue
            db = tuple(_f32(o.base[k] - fp.base[k]) for k in range(3))
            d = _f32(_f32(_f32(nrm[i][0] * db[0]) + _f32(nrm[i][1] * db[1]))
                     + _f32(nrm[i][2] * db[2]))
            if _f32(-0.001) < d < _f32(0.001):
                o.i_link = i


def _assign_content_ilinks(out: list[FPoly]) -> None:
    """`bspValidateBrush`'s LINK phase as the editor STORES it on an imported CONTENT brush's own
    shape model: run the same coplanar-fuse as `_assign_ilinks`, but a poly in NO multi-poly group
    keeps `iLink=-1` (the editor's unlinked sentinel) instead of its own index. Only a group MASTER
    (>=1 follower) keeps its index; followers point at the master.

    This differs from the live BUILDER brush (`_builder_cube_polys`, master=index even for a
    singleton). A 6-face cube is all singletons -> all -1, which is why every N<16 content brush
    matched with no link phase at all; `Brush1643`'s two coplanar `Side` walls (WanChai N=16) are the
    first real groups, and there the editor stores the master index on the wall, -1 elsewhere."""
    from collections import Counter
    _assign_ilinks(out)                                  # master=index, follower=master, singleton=index
    group_size = Counter(fp.i_link for fp in out)        # polys pointing at each master (incl. itself)
    for i, fp in enumerate(out):
        if fp.i_link == i and group_size[i] == 1:        # singleton -> the editor's -1 sentinel
            fp.i_link = -1


def _builder_cube_polys() -> list[FPoly]:
    """The synthesized builder brush's cube polys AS THE EDITOR SAVES THEM: `assemble`'s authored
    cube run through the SAME import finalize a content brush gets -- CalcNormal recomputes each
    normal from winding and bspValidateBrush assigns iLinks. Raw `_builder_cube_polys` (authored
    normals, no links) diverges from the editor's builder Polys body (byte-verified, N=1)."""
    polys = ASM._builder_cube_polys()
    for fp in polys:
        n = _calc_normal(fp.verts)
        if n is not None:
            fp.normal = n
    _assign_ilinks(polys)
    return polys


def _f32(x: float) -> float:
    import struct as _s
    return _s.unpack("<f", _s.pack("<f", x))[0]


def _calc_normal(verts) -> tuple | None:
    """`FPoly::CalcNormal` (Engine.dll 0x150510), byte-faithful f32 chain: summed cross products
    off vert 0, then `NormalizeSlow` -- magnitude as f32(sqrt_f64(f32 mag2)). The editor's T3D
    importer RECOMPUTES every poly normal this way, discarding the authored `Normal=` (an authored
    axis 1.0 comes back 0.99999994); byte parity requires reproducing it. Mirrors
    `uedcli-native/src/fpoly.rs::calc_normal`."""
    import math
    v = [tuple(_f32(c) for c in p) for p in verts]
    nx = ny = nz = 0.0
    x0, y0, z0 = v[0]
    for i in range(2, len(v)):
        ax, ay, az = _f32(v[i - 1][0] - x0), _f32(v[i - 1][1] - y0), _f32(v[i - 1][2] - z0)
        bx, by, bz = _f32(v[i][0] - x0), _f32(v[i][1] - y0), _f32(v[i][2] - z0)
        cx = _f32(_f32(ay * bz) - _f32(az * by))
        cy = _f32(_f32(az * bx) - _f32(ax * bz))
        cz = _f32(_f32(ax * by) - _f32(ay * bx))
        nx, ny, nz = _f32(nx + cx), _f32(ny + cy), _f32(nz + cz)
    mag2 = _f32(_f32(_f32(nx * nx) + _f32(ny * ny)) + _f32(nz * nz))
    if mag2 < 1e-8:
        return None
    inv = _f32(1.0 / _f32(math.sqrt(mag2)))
    return (_f32(nx * inv), _f32(ny * inv), _f32(nz * inv))


def _shape_bounds(polys: list[FPoly]) -> tuple | None:
    """A brush SHAPE model's computed local-space bbox + bounding sphere as
    `(bbox_min, bbox_max, sphere)`. The sphere is centered on the bbox midpoint with
    radius = sqrt(max per-VERTEX squared distance, f32 op chain) * 1.001 -- double-precision sqrt
    and multiply, narrowed to f32 once. NOT the bbox half-diagonal: a brush whose bbox corner is
    not an actual vertex gets a tighter sphere. Full 41-byte prefix verified against all 762
    brush shape models of the UNATCO import golden (2026-09-02; the old |extent|-based radius
    missed 144 of them by 1 ulp or more). None for an empty poly list (prefix stays zeroed)."""
    import math
    import struct as _s

    def f32(x: float) -> float:
        return _s.unpack("<f", _s.pack("<f", x))[0]

    vs = [tuple(f32(c) for c in v) for fp in polys for v in fp.verts]
    if not vs:
        return None
    mn = tuple(min(v[i] for v in vs) for i in range(3))
    mx = tuple(max(v[i] for v in vs) for i in range(3))
    center = tuple(f32(f32(mn[i] + mx[i]) * 0.5) for i in range(3))
    max_sq = max(f32(f32(f32(f32(v[0] - center[0]) * f32(v[0] - center[0]))
                         + f32(f32(v[1] - center[1]) * f32(v[1] - center[1])))
                     + f32(f32(v[2] - center[2]) * f32(v[2] - center[2]))) for v in vs)
    radius = f32(math.sqrt(max_sq) * f32(1.001))
    return mn, mx, (*center, radius)


def build_mover_shape_model(polys: list[FPoly]) -> tuple[UM.Model, list[int]]:
    """The editor's `csgPrepMovingBrush`, natively: build a MOVER's private shape-model BSP over
    its own local-space `polys` (as `_fpolys` produces them). UED22 builds one for every mover at
    `MAP IMPORT`/rebuild, so a saved map never ships a mover with an empty shape model.

    Returns `(model, links)`: a `umodel.Model` with the BSP arrays populated (nodes/surfs/verts/
    points/vectors/render bounds/collision leaf hulls, `NumSharedSides=4`,
    `RootOutside=Linked=1`, bbox+sphere computed from the polys) -- the caller still sets
    `none_index` and `field_0x54` -- and the per-poly `iLink` list the editor leaves in the
    mover's saved `Polys` (the assigned surf index for a poly the build consumed whole, the
    `bspValidateBrush` link for one it split). Byte-verified against all 28 built mover models +
    `Polys` bodies of the UNATCO import golden (2026-09-02). Requires the `uedcli_native`
    extension (heavy compute lives in Rust)."""
    import uedcli_native
    built, links = uedcli_native.build_brush_model(
        [([c for v in fp.verts for c in v], fp.base, fp.normal, fp.texture_u, fp.texture_v,
          fp.poly_flags, fp.texture_ref, fp.pan_u, fp.pan_v) for fp in polys])
    body = uedcli_native.serialize_model(built)
    m = UM.parse_model_body(body, 0, len(body))
    m.root_outside = m.linked = 1
    b = _shape_bounds(polys)
    if b is not None:
        m.bbox_min, m.bbox_max, m.sphere = b[0], b[1], b[2]
        m.bbox_valid = 1
    return m, links


def _world_soup_fpolys(asm, world_model, csg_brushes, tex_ref) -> list:
    """The world Model's `Polys` soup (`Model.Polys`): one `FPoly` per post-CSG world poly the
    native core retained (`umodel.Model.world_soup`). Resolves each poly's owner-brush export ref,
    texture import, and `Item=` name from its SOURCE brush poly (`i_actor`/`i_brush_poly`), the SAME
    provenance `_patch_native_surf_refs` uses for the surfs. The editor propagates the source poly's
    authored `ItemName` onto every world fragment it carves: an authored face (cube `Item=OUTSIDE`, a
    staircase `Rise`/`Step`/`Side`) keeps its label; a face with NO authored `Item` keeps the FPoly
    default `NAME_None` (serialized as the `None` FName), NOT `OUTSIDE`. `OUTSIDE` is not a CSG-fabricated
    default -- it is only ever an authored value (byte-measured on OceanLab N=3: ued's world soup has
    6 `OUTSIDE`, all from a cube brush's authored faces, and 168 `None`). An out-of-range `i_actor`
    leaves the poly ownerless/untextured and named `None`, never raising -- mirroring the surf patch."""
    from itertools import batched
    out = []
    for verts_flat, base, normal, tu, tv, pflags, i_actor, i_brush_poly, i_link, pan in \
            getattr(world_model, "world_soup", ()):
        actor_ref, texture_ref, item = 0, 0, None
        if 0 <= i_actor < len(csg_brushes):
            name, polys = csg_brushes[i_actor]
            actor_ref = asm.eref(name)
            if 0 <= i_brush_poly < len(polys):
                src = polys[i_brush_poly]
                if src.texture:
                    texture_ref = tex_ref(src.texture)
                if src.item is not None:
                    item = src.item
        out.append(FPoly(
            verts=[tuple(v) for v in batched(verts_flat, 3)],
            base=tuple(base), normal=tuple(normal), texture_u=tuple(tu), texture_v=tuple(tv),
            poly_flags=pflags, actor_ref=actor_ref, texture_ref=texture_ref, item=item,
            i_link=i_link, i_brush_poly=i_brush_poly, pan_u=pan[0], pan_v=pan[1]))
    return out


def _patch_native_surf_refs(asm, model, csg_brushes, tex_ref) -> None:
    """Rewrite every surf of a NATIVELY built world Model to real object refs: `iActor` (a raw
    brush index the Rust build tags) -> the brush actor's export ref, and `texture_ref` (always 0
    out of the build -- the CSG core never sees textures) -> the import the source poly's `Texture=`
    names, through the SAME `tex_ref` resolver the brush polys used, so an unqualified trunk texture
    resolves identically on both. An out-of-range index leaves the surf ownerless/untextured rather
    than raising -- the same guard `preview_native._node_polys` applies."""
    for s in model.surfs:
        bi = s.i_actor
        if not (0 <= bi < len(csg_brushes)):
            s.i_actor = 0                                # unknown owner -> none
            continue
        name, polys = csg_brushes[bi]
        s.i_actor = asm.eref(name)
        if 0 <= s.i_brush_poly < len(polys):
            tex = polys[s.i_brush_poly].texture
            if tex:
                s.texture_ref = tex_ref(tex)


# The six viewport Camera actors + the LevelSummary a fresh UED22 session serializes into every
# MAP SAVE (retail maps carry them too; UNATCO import golden, 2026-09-02). Camera VIEWPORT STATE
# (ShowFlags/RendMap/OldLocation/...) is editor-session output inside the parity exclusion mask;
# these fixed values pin the byte layout only.
_FLAGS_CAMERA = 0x02340000
_FLAGS_SUMMARY = 0x00070004
_CAMERA_OLD_LOCATION = (-500.0, -300.0, 300.0)

# The ALWAYS-synthesized simple builder brush (owner ruling, 2026-09-03): UED22 adopts Actors[1]
# as its red builder brush and excludes it from CSG at every rebuild -- live-measured, even the
# editor's OWN import-save loses its first content brush's geometry at any later `MAP REBUILD`.
# The shape name `Brush` is `normalize.BUILDER_BRUSH_MODEL_NAME`, so the post-verify recognises
# and drops the actor; `Polys4` is the counter name the editor's own builder polys would carry. A
# trunk actor colliding with these names raises `_reserve`'s duplicate error (clean exit 2).
_BUILDER = "DefaultBrush"
_BUILDER_SHAPE = "Brush"
# (name, ShowFlags, RendMap, Tag, Misc1, bHidden, Location, bHiddenEd)
_CAMERAS = (
    ("Camera6", 1997, 13, "U2Viewport0", None, False, None, True),
    ("Camera7", 1993, 14, "U2Viewport1", None, False, None, True),
    ("Camera8", 1993, 5, "U2Viewport2", None, False, None, False),
    ("Camera9", 1993, 15, "U2Viewport3", None, False, None, True),
    ("Camera10", 8832, 18, "MeshBrowser", None, False,
     (-655.7438354492188, -0.0, -0.0), False),
    ("Camera11", 8832, 17, "TextureBrowser", 128, True, None, True),
)


def _camera_props(li_name: str, showflags, rendmap, tag, misc1, hidden, location,
                  hidden_ed) -> list:
    """One viewport Camera actor's props (unordered -- `_actor_body` rank-sorts)."""
    props = [Prop("Player", AW.PT_OBJECT, 0),
             Prop("ShowFlags", AW.PT_INT, showflags),
             Prop("RendMap", AW.PT_INT, rendmap),
             Prop("bAdmin", AW.PT_BOOL, True),
             _pointregion_prop("FootRegion", zone=li_name),
             _pointregion_prop("HeadRegion", zone=li_name),
             Prop("Level", AW.PT_OBJECT, ASM.ObjRef(li_name)),
             Prop("Tag", AW.PT_NAME, tag),
             Prop("Base", AW.PT_OBJECT, ASM.ObjRef(li_name)),
             _pointregion_prop("Region", zone=li_name),
             Prop("OldLocation", AW.PT_STRUCT,
                  AW.struct_vector(*_CAMERA_OLD_LOCATION), struct_name="Vector")]
    if misc1 is not None:
        props.append(Prop("Misc1", AW.PT_INT, misc1))
    if hidden:
        props.append(Prop("bHidden", AW.PT_BOOL, True))
    if location is not None:
        props.append(Prop("Location", AW.PT_STRUCT,
                          AW.struct_vector(*location), struct_name="Vector"))
    if hidden_ed:
        props.append(Prop("bHiddenEd", AW.PT_BOOL, True))
    return props


def _actor_body(asm, name: str, qualified_class: str, props: list, rank_for,
                warnings: list) -> bytes:
    """StateFrame + tagged props in the editor's SERIALIZATION order
    (`class_serialization_order`): rank by name, static-array elements by index, unknown names
    last in build order (stable sort)."""
    try:
        rank = rank_for(qualified_class)
    except Exception as e:
        rank = {}
        warnings.append(f"{qualified_class}: no serialization order ({e}); emitting build order")
    ordered = sorted(props, key=lambda p: (rank.get(p.name.casefold(), len(rank)),
                                           p.array_index or 0))
    return (AW.state_frame(asm.exports[asm.index_of[name]].cls)
            + AW.write_props(asm.name_index,
                             [asm._resolve_prop_value(p) for p in ordered]))


def _seed_tables(asm, pkg) -> None:
    """PARITY-GATE oracle injection, never set in production: pre-intern the golden's name table
    and replay its import table so the two linker-order unknowns (name/import order -- editor
    hash-map iteration artifacts, see the 2026-09-02 spike) come from the oracle and every OTHER
    byte is judged by the gate."""
    for n in pkg.names:
        asm.name_index(n)
    # Verbatim table copy (the golden's own order can FORWARD-reference an outer sub-package, so
    # a parent-first replay through the resolver cannot reproduce it), then register each entry in
    # the resolver's memos so assembly lookups reuse these entries instead of minting new ones.
    from .codec import ref_import
    from .pkg_write import ImportRec
    for j, (cp, cn, pi, on) in enumerate(pkg.imports):
        kind = pkg.names[cn]
        chain, ref = [], pi
        while ref < 0:
            k = -ref - 1
            chain.append(pkg.names[pkg.imports[k][3]])
            ref = pkg.imports[k][2]
        outer = ".".join(reversed(chain))
        name = pkg.names[on]
        asm.resolver.imports.append(ImportRec(
            class_package=asm.name_index(pkg.names[cp]), class_name=asm.name_index(kind),
            package_index=pi, object_name=asm.name_index(name)))
        r = ref_import(j)
        if kind == "Package":
            asm.resolver._pkg[f"{outer}.{name}" if outer else name] = r
        elif kind == "Class":
            asm.resolver._cls[(outer, name)] = r
        else:
            asm.resolver._obj[(f"{outer}", kind, name)] = r


def _map_import_load_files(level, pkg_dirs) -> list[tuple[str, str]]:
    """The editor's OBJ-LOAD manifest resolved to (pkg_name, host_file), in the same
    sorted `_level_referenced_packages` order the golden `MAP IMPORT` used -- the input
    to the import-table creation-order model."""
    from uedcli.apply import _level_referenced_packages
    from uedcli.packages import obj_load_entries
    return obj_load_entries(_level_referenced_packages(level),
                            [d for d in (pkg_dirs or ()) if d])


def _map_import_t3d(level) -> str:
    """The whole-level T3D the editor's `MAP IMPORT` consumes, in its import
    (`levelinfo_first_order`) order -- the map-time name creation sequence's source."""
    from uedcli.emit import emit_map
    from uedcli.materialize import levelinfo_first_order
    classes = {n: level.actors[n].cls for n in level.order}
    has_brush = {n: level.actors[n].brush is not None for n in level.order}
    order = levelinfo_first_order(level.order, classes, has_brush)
    return emit_map([level.actors[n] for n in order])


def assemble_unbuilt(level, *, version: int = 69, level_name: str = "MyLevel",
                     schema=None, pkg_dirs=None, world_model=None, csg_brushes=None,
                     zone_actors=None, light_names=None, table_oracle=None):
    """`assemble_level` with an EMPTY world Model and REAL per-brush polys.

    `schema` is the `ImportSchema` (or bare `schema_lookup` callback) that types every actor prop
    (`substrate_schema`). `pkg_dirs` are the package search dirs; they carry two indexes a real level
    cannot do without: the class -> defining-package map (so `DeusExMover` imports from `DeusEx`, not
    `Engine`) and the texture group map (so a poly's 2-part `Package.Name` becomes the
    `Package.Group.Name` the game requires). Omit them only for an engine-classes-only probe level.

    When `pkg_dirs` are given and no `table_oracle` is passed, the name/import tables are made
    editor-identical with NO oracle via a TWO-PASS build: pass 1 assembles with insertion-order
    tables, then `saveorder.compute_tables` derives the editor's `MAP SAVE` name/import order (the
    reverse-engineered creation-order + count-descending `appQsort` model, spike 2026-09-02) and
    pass 2 re-assembles with those tables pre-seeded. Import order is byte-exact; name order is exact
    but for a UNATCO-scale placed-actor sub-order residual (owner-excluded from the parity bar).
    An explicit `table_oracle` (parity-gate golden seeding) skips the two pass.

    `world_model` opts out of the empty world Model: pass a BUILT `umodel.Model`
    (`materialize.build_world_model`) plus its `csg_brushes` join list and `zone_actors` map and the
    package ships that BSP, so the editor has nothing left to rebuild (`MAP LOAD` without
    `MAP REBUILD`). Mover brush models stay unbuilt either way -- only `MAP REBUILD` builds those.

    `light_names` is the ordered light-actor name list the baked Model's `lights` array indexes
    (`materialize.gather_lights`, index i == light i): assembly rewrites those indexes to the actors'
    export refs.

    MUTATES `level`: `rewrite_self_package_refs` requalifies the level's own package refs to
    `MyLevel.` before anything is typed, because a package that skipped it ships unloadable.

    Returns `(package_bytes, warnings)`."""
    rewrite_self_package_refs(level)
    # Two-pass generative tables (spike 2026-09-02): pass 1 assembles with insertion-order tables,
    # then `saveorder.compute_tables` derives the editor's count-descending `MAP SAVE` name/import
    # order and pass 2 re-seeds it. Covers the BUILT path too (`world_model` given -- the SavePackage
    # qsort runs on every save): its `_patch_*` MUTATE the model, so each pass gets its own deep copy.
    # An explicit `table_oracle` (parity-gate golden seeding) skips the two-pass.
    if pkg_dirs and table_oracle is None:
        import copy
        from uedcli.native.saveorder import compute_tables, map_name_sequence
        load_files = _map_import_load_files(level, pkg_dirs)
        pass1, _w1 = _assemble_once(
            level, version=version, level_name=level_name, schema=schema, pkg_dirs=pkg_dirs,
            world_model=copy.deepcopy(world_model), csg_brushes=csg_brushes,
            zone_actors=zone_actors, light_names=light_names, table_oracle=None)
        spec = compute_tables(pass1, load_files,
                              map_name_sequence(pass1, _map_import_t3d(level)))
        return _assemble_once(
            level, version=version, level_name=level_name, schema=schema, pkg_dirs=pkg_dirs,
            world_model=copy.deepcopy(world_model), csg_brushes=csg_brushes,
            zone_actors=zone_actors, light_names=light_names, table_oracle=spec)
    return _assemble_once(
        level, version=version, level_name=level_name, schema=schema, pkg_dirs=pkg_dirs,
        world_model=world_model, csg_brushes=csg_brushes, zone_actors=zone_actors,
        light_names=light_names, table_oracle=table_oracle)


def _assemble_once(level, *, version: int = 69, level_name: str = "MyLevel",
                   schema=None, pkg_dirs=None, world_model=None, csg_brushes=None,
                   zone_actors=None, light_names=None, table_oracle=None):
    """One assembly pass (`level` already `rewrite_self_package_refs`-normalised). With
    `table_oracle` (a golden `Package` or a `saveorder.TableSpec`) the name/import tables
    come pre-seeded; without it they are insertion-order."""
    actors, brush_actors, warnings = _trunk_to_actorspecs(level, schema or (lambda fqcn: {}),
                                                          world_model=world_model)
    present = {a.name for a in actors + brush_actors}
    for spec in actors + brush_actors:
        spec.props = [_internal_ref(pr, present, spec.name, warnings) for pr in spec.props]

    class_packages, texture_groups, texture_kinds = {}, {}, {}
    if pkg_dirs:
        from uedcli.native.pkgref import build_class_package_index, build_texture_group_index
        class_packages = build_class_package_index(pkg_dirs)
        # `Texture` alone misses the animated subclasses a real level uses (`WetTexture`,
        # `FireTexture`, ...), which then look unresolvable and fail the build.
        texture_groups = build_texture_group_index(pkg_dirs, kinds=_TEXTURE_KINDS)
        texture_kinds = _texture_kind_index(pkg_dirs)
    seeded_names = None
    if table_oracle is not None:
        from .pkg_write import NameTable
        seeded_names = NameTable()
        for n in table_oracle.names:
            seeded_names.index(n)
    asm = ASM._Assembler(version, level_name, texture_groups=texture_groups,
                         class_packages=class_packages, names=seeded_names)
    if table_oracle is not None:
        _seed_tables(asm, table_oracle)

    # A T3D export stores textures UNQUALIFIED, and 49 of Deus Ex's 2389 texture names live in two
    # or more packages. The EDITOR resolves such a name against its loaded packages in OBJ LOAD
    # order -- the referenced-package list in raw ASCII sort, capitals before lowercase (measured:
    # `Area51Wall_A` -> `CoreTexMetal`, not `area51textures`, on the UNATCO import golden,
    # 2026-09-02) -- so the writer picks the ASCII-first ORIGINAL-CASE package stem, never a
    # level-usage heuristic.
    by_name: dict[str, set[str]] = {}
    for (pkg_stem, obj), _group in texture_groups.items():
        by_name.setdefault(obj, set()).add(pkg_stem)
    stem_case: dict[str, str] = {}
    for d in (x for x in (pkg_dirs or ()) if x):
        for f in list(Path(d).glob("*.utx")) + list(Path(d).glob("*.u")):
            stem_case.setdefault(f.stem.casefold(), f.stem)

    from uedcli.apply import _level_referenced_packages
    ref_pkgs = {p.casefold() for p in _level_referenced_packages(level)}

    def tex_ref(name: str) -> int:
        if name.casefold() in ("none", ""):        # T3D's spelling for "no texture"
            return 0
        # The editor's importer binds a poly texture by BARE NAME even when the T3D qualifies it
        # (measured: trunk `area51textures.Area51Wall_A` -> golden `CoreTexMetal.Metal...`), so
        # the qualifier is dropped and the name resolves against the level's referenced packages
        # in OBJ LOAD order (raw ASCII sort of original-case stems).
        base = name.split(".")[-1].casefold()
        candidates = by_name.get(base, set())
        if not candidates:
            if "." in name:                        # explicit qualifier, name not in the scan index
                head = name.split(".")[0].casefold()
                return asm.resolver.object_ref(texture_kinds.get((head, base), "Texture"), name)
            raise ValueError(f"texture {name!r} is not in any package on the search path -- a "
                             f"substituted default is not acceptable, fix the search path")
        loaded = candidates & ref_pkgs
        pkg_stem = min(loaded or candidates, key=lambda s: stem_case.get(s, s))
        return asm.resolver.object_ref(texture_kinds.get((pkg_stem, base), "Texture"),
                                       f"{stem_case.get(pkg_stem, pkg_stem)}.{name.split('.')[-1]}")

    # UED22 stamps its own engine defaults into the saved URL (`unreal://...:7777`), regardless of
    # the game the content targets (UNATCO import golden, 2026-09-02).
    url = URL(protocol="unreal", port=7777,
              map=("Index.unr" if version >= 69 else "Index.dx"))

    # Schema search path for the base-stamp/mover class decisions below: the game's own v68 `.u`
    # (bCollideWorld/ancestry answered as the game declares them).
    schema_paths: dict[str, str] = {}
    for d in (x for x in (pkg_dirs or ()) if x):
        for f in Path(d).glob("*.u"):
            schema_paths.setdefault(f.stem.casefold(), str(f))

    # The editor's tagged-property SERIALIZATION order, per class, MUST come from the UED22
    # substrate (`.u` the editor itself iterates at MAP SAVE), NOT the game's v68 `.u` -- the two
    # disagree on prop order: e.g. `Engine.Actor.AmbientSound` ranks after `SoundVolume` in the
    # game schema but right after `Tag` in UED22, the order the golden carries. So the rank
    # resolver shadows any game copy of a package with the UED22 one.
    from uedcli import tool_assets
    from uedcli.uprops.uclass import class_serialization_order
    rank_schema_paths: dict[str, str] = {}
    for d in [str(tool_assets.uned_dir() / "UED22"), *(x for x in (pkg_dirs or ()) if x)]:
        for f in Path(d).glob("*.u"):
            rank_schema_paths.setdefault(f.stem.casefold(), str(f))
    rank_pkgs: dict = {}
    ranks: dict[str, dict[str, int]] = {}

    def rank_for(fqcn: str) -> dict[str, int]:
        r = ranks.get(fqcn.casefold())
        if r is None:
            r = class_serialization_order(
                fqcn, resolver=lambda p: rank_schema_paths.get(p.casefold()), _pkgs=rank_pkgs)
            ranks[fqcn.casefold()] = r
        return r

    li = next((a for a in actors if a.is_level_info), None)
    li_name = li.name if li else "LevelInfo0"
    asm.levelinfo_name = li_name

    # The editor's SpawnActor->FindBase stamps `Base=<the LevelInfo>` at SPAWN, before the T3D props
    # apply, so the decision reads CLASS-DEFAULT flags: it fires iff bCollideWorld AND
    # IsA(Decoration|Inventory|Pawn). No physics clause, no bStatic clause -- both refuted by the
    # 27-class UED22 matrix (spike 2026-09-04-base-stamp-rule): Falling/Rotating/Rolling/Swimming/
    # Flying decos+pawns are all stamped; static CarWrecked/FirePlug are stamped; Effects/Projectile
    # (Spark/GasGrenade) are NOT, by ancestry; SecurityCamera (bCollideWorld=False) is NOT. Inventory
    # is inert here (no concrete Inventory class defaults bCollideWorld=True) but kept faithful to the
    # editor's IsA set. An authored `Base` wins (spawn precedes T3D apply), so it is never restamped.
    from uedcli.classdefaults import ClassDefaults
    from uedcli.classindex import ClassIndex
    cdefaults = ClassDefaults(lambda p: schema_paths.get(p.casefold()))
    class_index = ClassIndex.from_files(sorted(set(schema_paths.items())))
    _BASE_STAMP_ANCESTORS = ("Engine.Decoration", "Engine.Inventory", "Engine.Pawn")

    def _base_stamped(name: str) -> bool:
        a = level.actors.get(name)
        if a is None or any(k.split("(")[0].casefold() == "base" for k, _v in a.props):
            return False
        try:
            d = cdefaults.for_class(a.cls).defaults
        except Exception:
            return False
        if str(d.get(("bcollideworld", 0))) != "True":
            return False
        return any(class_index.descends_from(a.cls, base) for base in _BASE_STAMP_ANCESTORS)

    def _li_body():
        # Level->self plus the editor's save-time stamps: TimeSeconds/AIProfile (session clock and
        # counters -- inside the parity exclusion mask, emitted as zeros to pin the layout) and
        # Summary -> the LevelSummary export.
        props = [Prop("Level", AW.PT_OBJECT, ASM.ObjRef(li_name)),
                 Prop("TimeSeconds", AW.PT_FLOAT, 0.0),
                 Prop("AIProfile", AW.PT_INT, 0),
                 Prop("Summary", AW.PT_OBJECT, ASM.ObjRef("LevelSummary"))]
        # When the trunk carries the LevelInfo, its spec already holds the editor's stamps (Tag from
        # the T3D, Region kept solid by `_trunk_to_actorspecs`). When it does NOT (the LevelInfo is
        # not among the first-N actors), synthesize what the editor spawns for any LevelInfo: the
        # class-default Tag and a solid Region (Zone=self, iLeaf=-1, ZoneNumber=0) -- byte-measured on
        # Island N=1, whose golden LevelInfo carries exactly Tag='LevelInfo' + Region(-1,0).
        extra = list(li.props) if li else [
            Prop("Tag", AW.PT_NAME, "LevelInfo"),
            _pointregion_prop("Region", zone=li_name)]
        return _actor_body(asm, li_name, "Engine.LevelInfo", props + extra, rank_for, warnings)
    ASM._reserve_actor(asm, li_name, "Engine.LevelInfo", _li_body, flags=ASM._FLAGS_ACTOR)

    # The world Model + its empty Polys child carry the editor's fixed fresh-session names
    # (`Model2`/`Polys3`); there is NO synthesized builder brush -- a `MAP IMPORT` save has none
    # (the first content brush is hoisted into the builder's Actors[1] slot instead). Reservation
    # order below IS the editor's export-table order, emulated exactly (the closed form at the
    # `ordered` block; element-exact on all four 2026-09-02 import goldens).
    wm_polys, wm_name = "Polys3", "Model2"

    if world_model is None:
        wm = UM.Model()
        wm.none_index = asm.name_index("None")
        wm.num_shared_sides = 4                          # the editor's fresh world model constant

        def _world_model_body():
            wm.field_0x54 = asm.eref(wm_polys)
            return UM.write_model_body(wm)
    else:
        world_model.none_index = asm.name_index("None")

        def _world_model_body():
            world_model.field_0x54 = asm.eref(wm_polys)
            _patch_native_surf_refs(asm, world_model, csg_brushes or [], tex_ref)
            ASM._patch_zone_refs(asm, world_model, zone_actors)
            ASM._patch_light_refs(asm, world_model, light_names)
            return UM.write_model_body(world_model)

    others = [a for a in actors if not a.is_level_info]
    points = [a for a in others if not a.is_brush]

    def _point_desc(a):
        def _body(a=a):
            authored = list(a.props)
            has_level = any(getattr(p, "name", "").casefold() == "level" for p in authored)
            props = authored if has_level else \
                [Prop("Level", AW.PT_OBJECT, ASM.ObjRef(li_name))] + authored
            if _base_stamped(a.name):
                props = props + [Prop("Base", AW.PT_OBJECT, ASM.ObjRef(li_name))]
            return _actor_body(asm, a.name, a.qualified_class, props, rank_for, warnings)
        return (a.name, a.qualified_class, ASM._FLAGS_ACTOR, _body)

    def _shape_model_body(polys_name: str, polys: list) -> bytes:
        # A brush SHAPE model carries a COMPUTED local-space bbox + bounding sphere
        # (`_shape_bounds`), NumSharedSides=4 and RootOutside=Linked=1 -- all verified against
        # the UNATCO import golden's per-brush models (2026-09-02).
        m = UM.Model(none_index=asm.name_index("None"))
        m.field_0x54 = asm.eref(polys_name)
        m.num_shared_sides = 4
        m.root_outside = m.linked = 1
        b = _shape_bounds(polys)
        if b is not None:
            m.bbox_min, m.bbox_max, m.sphere = b[0], b[1], b[2]
            m.bbox_valid = 1
        return UM.write_model_body(m)

    # A MOVER is a dynamic actor the GAME loads: the golden marks the mover actor 0x02070001 and
    # its shape Model 0x00070001 (load-all), unlike a static brush's edit-only 0x02340001/0x00340001.
    from uedcli.movers import is_mover  # class_index built above (base-stamp gate)

    def _is_mover(name: str) -> bool:
        a = level.actors.get(name)
        try:
            return a is not None and is_mover(a, class_index)
        except Exception:
            return False

    def _brush_desc(b):
        def _bbody(b=b):
            props = [Prop("Level", AW.PT_OBJECT, ASM.ObjRef(li_name)),
                     Prop("Brush", AW.PT_OBJECT, ASM.ObjRef(f"Model_{b.name}"))] + list(b.props)
            if _base_stamped(b.name):
                props = props + [Prop("Base", AW.PT_OBJECT, ASM.ObjRef(li_name))]
            return _actor_body(asm, b.name, b.qualified_class, props, rank_for, warnings)
        return (b.name, b.qualified_class,
                ASM._FLAGS_ACTOR if _is_mover(b.name) else ASM._FLAGS_BRUSH_ACTOR, _bbody)

    def _cam_desc(cam):
        return (cam[0], "Engine.Camera", _FLAGS_CAMERA,
                (lambda c=cam: _actor_body(asm, c[0], "Engine.Camera",
                                           _camera_props(li_name, *c[1:]),
                                           rank_for, warnings)))

    _levelsummary_desc = ("LevelSummary", "Engine.LevelSummary", _FLAGS_SUMMARY,
                          lambda: AW.write_props(asm.name_index,
                                                 [Prop("Title", AW.PT_STR, "Untitled")]))

    # The creation STREAM: points, brush actors, then per-brush (Model, Polys) pairs -- the editor
    # builds the shape models in a post pass -- with LevelSummary created just before the last
    # Polys. Brush i's Polys is counter-named `Polys(6+2i)` (2 ticks per brush; 3..5 consumed at
    # MAP NEW).
    stream = [_point_desc(a) for a in points] + [_brush_desc(b) for b in brush_actors]
    for i, b in enumerate(brush_actors):
        shape, polys_name = f"Model_{b.name}", f"Polys{6 + 2 * i}"
        src = level.actors.get(b.name)
        polys = _fpolys(src.brush, tex_ref, actor=b.name) if src is not None and src.brush else []
        if _is_mover(b.name) and polys:
            # A MOVER ships its BUILT private shape model (`csgPrepMovingBrush`); the build also
            # reassigns the saved polys' iLinks (surf index for a whole-consumed poly, the
            # validate link for a split one).
            def _mover_model_body(pn=polys_name, p=polys):
                m, links = build_mover_shape_model(p)
                for fp, ln in zip(p, links):
                    fp.i_link = ln
                m.none_index = asm.name_index("None")
                m.field_0x54 = asm.eref(pn)
                return UM.write_model_body(m)
            stream.append((shape, "Engine.Model", ASM._FLAGS_LOAD, _mover_model_body))
        else:
            stream.append((shape, "Engine.Model",
                           ASM._FLAGS_LOAD if _is_mover(b.name) else ASM._FLAGS_BRUSH,
                           (lambda pn=polys_name, p=polys: _shape_model_body(pn, p))))
        if i == len(brush_actors) - 1:
            stream.append(_levelsummary_desc)
        stream.append((polys_name, "Engine.Polys", ASM._FLAGS_BRUSH_POLYS,
                       (lambda p=polys: AW.write_upolys_body(asm.name_index, p))))
    if not brush_actors:
        # A brushless subset (LevelInfo-only or point-only -- the lockstep ladder's early N) has no
        # per-brush loop to splice LevelSummary into, yet the LevelInfo body still refs it. Append it
        # so the export exists; its exact position vs the editor is a later ladder step.
        stream.append(_levelsummary_desc)

    def _level_body():
        # Actors[1] is a SYNTHESIZED simple builder brush (owner ruling, 2026-09-03): UED22
        # adopts Actors[1] as its red builder brush and keeps it OUT of CSG at every rebuild --
        # live-measured, the editor's own import-save loses its first content brush's geometry at
        # any later `MAP REBUILD` (same-session or after reload). Feeding it a sacrificial
        # builder keeps every content brush carving. This is the one ruled deviation from the
        # import-golden byte layout.
        refs = ([asm.eref(li_name), asm.eref(_BUILDER)]
                + [asm.eref(a.name) for a in points]
                + [asm.eref(b.name) for b in brush_actors]
                + [asm.eref(c[0]) for c in _CAMERAS])
        return write_level_body(none_index=asm.name_index("None"), actor_refs=refs,
                                model_ref=asm.eref(wm_name), url=url, reach_specs=None)

    # EXPORT-TABLE order: the closed form derived element-exact from the four 2026-09-02 import
    # goldens -- preamble [Polys3, Camera6, Camera7, Model2] after the LevelInfo, the object at
    # stream rank R = (n_points + 3*n_brushes - 1) // 2 hoisted into the last freed low slot with
    # Camera11 in its stream position, then Camera8..10 + the ULevel last -- with the ruled
    # always-present builder brush triple (`Polys4`/`Brush`/`DefaultBrush`, the editor's own
    # counter names) spliced in right after the LevelInfo.
    # The synthesized builder sits at the origin; its Region resolves the same way (built world ->
    # descend at (0,0,0); unbuilt -> solid).
    builder_leaf, builder_zone = (
        _model_point_region(world_model, (0.0, 0.0, 0.0))
        if world_model is not None and getattr(world_model, "nodes", None) else (-1, 0))
    builder = [
        ("Polys4", "Engine.Polys", ASM._FLAGS_LOAD,
         lambda: AW.write_upolys_body(asm.name_index, _builder_cube_polys())),
        # The editor builds the builder brush's SHAPE model at import (`csgPrepBrush`), so it ships
        # with the cube's computed bbox+sphere and RootOutside=Linked=1 -- same as any content shape
        # model, byte-verified against the ref builder (`Model Brush`, N=1). An empty model diverges.
        (_BUILDER_SHAPE, "Engine.Model", ASM._FLAGS_BRUSH,
         lambda: _shape_model_body("Polys4", _builder_cube_polys())),
        # The editor spawn-stamps `Tag=Brush` (Engine.Brush's class-default Tag) and a `Region`
        # PointRegion (Zone=<the LevelInfo>) on the imported builder, exactly as it does every content
        # actor. `_actor_body` rank-sorts to the editor order Level/Tag/Region/Brush.
        (_BUILDER, "Engine.Brush", ASM._FLAGS_BRUSH_ACTOR,
         lambda: _actor_body(asm, _BUILDER, "Engine.Brush",
                             [Prop("Level", AW.PT_OBJECT, ASM.ObjRef(li_name)),
                              Prop("Tag", AW.PT_NAME, "Brush"),      # Engine.Brush class-default Tag
                              _pointregion_prop("Region", zone=li_name,
                                                i_leaf=builder_leaf, zone_number=builder_zone),
                              Prop("Brush", AW.PT_OBJECT, ASM.ObjRef(_BUILDER_SHAPE))],
                             rank_for, warnings)),
    ]
    R = (len(points) + 3 * len(brush_actors) - 1) // 2
    if 0 <= R < len(stream):
        mid = [stream[R]] + [d if i != R else _cam_desc(_CAMERAS[5])
                             for i, d in enumerate(stream)]
    else:                                            # empty level: nothing to hoist
        mid = list(stream) + [_cam_desc(_CAMERAS[5])]
    # The world Model's Polys = the post-CSG soup the native core retained (empty for a brushless
    # world / the unbuilt empty-Model path).
    def _world_polys_body():
        soup = (_world_soup_fpolys(asm, world_model, csg_brushes or [], tex_ref)
                if world_model is not None else [])
        return AW.write_upolys_body(asm.name_index, soup)

    ordered = (builder
               + [(wm_polys, "Engine.Polys", ASM._FLAGS_LOAD, _world_polys_body),
                  _cam_desc(_CAMERAS[0]), _cam_desc(_CAMERAS[1]),
                  (wm_name, "Engine.Model", ASM._FLAGS_LOAD, _world_model_body)]
               + mid
               + [_cam_desc(c) for c in _CAMERAS[2:5]]
               + [(level_name, "Engine.Level", ASM._FLAGS_LEVEL, _level_body)])
    for name, qcls, flags, body in ordered:
        asm._reserve(name, qcls, flags, body)
    return asm.build(), warnings
