[URL]
Protocol=unreal
ProtocolDescription=Unreal Protocol
Name=Player
Map=Index.unr
LocalMap=UT-Logo-map.unr
Host=
Portal=
MapExt=dx
SaveExt=usa
Port=7777
Class=Botpack.TMale1

[FirstRun]
FirstRun=469

[PackageRemap]
UnrealShare=UnrealI

[Engine.Engine]
GameRenderDevice=OpenGLDRV.OpenGLRenderDevice
AudioDevice=Galaxy.GalaxyAudioSubsystem
NetworkDevice=IpDrv.TcpNetDriver
DemoRecordingDevice=udemo.udemodriver
Console=UTMenu.UTConsole
Language=int
GameEngine=Engine.GameEngine
EditorEngine=Editor.EditorEngine
WindowedRenderDevice=OpenGLDrv.OpenGLRenderDevice
RenderDevice=GlideDrv.GlideRenderDevice
DefaultGame=Botpack.DeathMatchPlus
DefaultServerGame=Botpack.DeathMatchPlus
ViewportManager=WinDrv.WindowsClient
Render=Render.Render
Input=Engine.Input
Canvas=Engine.Canvas
CdPath=F:
RunCount=0

[Core.System]
PurgeCacheDays=0
SavePath=../Save
CachePath=../Cache
CacheExt=.uxx
Suppress=DevLoad
Suppress=DevSave
Suppress=DevNetTraffic
Suppress=DevGarbage
Suppress=DevKill
Suppress=DevReplace
Suppress=DevSound
Suppress=DevCompile
Suppress=DevBind
Suppress=DevBsp
Paths=../UED22/*.u
Paths=../Maps/*.dx
Paths=../Textures/*.utx
Paths=../Sounds/*.uax
Paths=../Music/*.umx
Paths=../LUM/System/*.u
Paths=../LUM/Maps/*.dx
Paths=../LUM/Textures/*.utx
Paths=../LUM/Sounds/*.uax
Paths=../LUM/Music/*.umx
Suppress=DevMD5
Suppress=DevMusic

[Engine.GameEngine]
CacheSizeMegs=4
UseSound=True

[WinDrv.WindowsClient]
WindowedViewportX=1656
WindowedViewportY=1040
WindowedColorBits=32
FullscreenViewportX=1024
FullscreenViewportY=768
FullscreenColorBits=32
Brightness=0.600000
MipFactor=1.000000
UseDirectDraw=True
UseJoystick=False
CaptureMouse=True
StartupFullscreen=False
CurvedSurfaces=False
LowDetailTextures=False
ScreenFlashes=True
NoLighting=False
SlowVideoBuffering=True
DeadZoneXYZ=True
DeadZoneRUV=False
InvertVertical=False
ScaleXYZ=1000.000000
ScaleRUV=2000.000000
MinDesiredFrameRate=28.000000
Decals=True
NoDynamicLights=False
UseDirectInput=False
ParticleDensity=0
NoFractalAnim=False
SkinDetail=High
TextureDetail=High
NoEnhancedPointerPrecision=true
WinPosY=-1
WinPosX=-1
UseRawHIDInput=False
InhibitWindowsHotkeys=False
FrameRateLimit=0.000000

[XDrv.XClient]
WindowedViewportX=640
WindowedViewportY=480
WindowedColorBits=32
FullscreenViewportX=640
FullscreenViewportY=480
FullscreenColorBits=32
Brightness=0.500000
MipFactor=1.000000
SlowVideoBuffering=False
StartupFullscreen=False
CurvedSurfaces=False
CaptureMouse=True
LowDetailTextures=False
ScreenFlashes=True
NoLighting=False
DeadZoneXYZ=True
DeadZoneRUV=False
InvertVertical=False
ScaleXYZ=1000.0
ScaleRUV=2000.0
MinDesiredFrameRate=30.0

[Engine.Player]
ConfiguredInternetSpeed=25000
ConfiguredLanSpeed=20000

[Audio.GenericAudioSubsystem]
UseFilter=True
UseSurround=False
UseStereo=True
UseCDMusic=False
UseDigitalMusic=False
UseSpatial=False
UseReverb=False
Use3dHardware=False
LowSoundQuality=False
ReverseStereo=False
Latency=40
OutputRate=22050Hz
Channels=16
MusicVolume=160
SoundVolume=255
AmbientFactor=0.7

[Galaxy.GalaxyAudioSubsystem]
UseDirectSound=True
UseFilter=True
UseSurround=False
UseStereo=True
UseCDMusic=False
UseDigitalMusic=True
UseSpatial=False
UseReverb=True
Use3dHardware=False
LowSoundQuality=False
ReverseStereo=False
Latency=40
OutputRate=44100Hz
EffectsChannels=16
DopplerSpeed=9000.000000
MusicVolume=128
SoundVolume=255
AmbientFactor=0.700000
DetailStats=False

[IpDrv.TcpNetDriver]
AllowDownloads=True
ConnectionTimeout=15.0
InitialConnectTimeout=150.000000
AckTimeout=1.0
KeepAliveTime=0.200000
MaxClientRate=25000
SimLatency=0
RelevantTimeout=5.000000
SpawnPrioritySeconds=1.000000
ServerTravelPause=4.000000
NetServerMaxTickRate=20
LanServerMaxTickRate=35
ConnectionTimeout=45.000000
OverrideBufferAllocation=False
DownloadManagers=IpDrv.HTTPDownload
DownloadManagers=Engine.ChannelDownload
MaxDownloadSize=0
MaxConnPerIPPerMinute=5
LogMaxConnPerIPPerMin=False
AllowPlayerPortUnreach=True
LogPortUnreach=False
MaxFileDownloadRate=-1

[Engine.DemoRecDriver]
DemoSpectatorClass=Botpack.CHSpectator
MaxClientRate=25000
ConnectionTimeout=15.0
InitialConnectTimeout=500.0
AckTimeout=1.0
KeepAliveTime=1.0
SimLatency=0
RelevantTimeout=5.0
SpawnPrioritySeconds=1.0
ServerTravelPause=4.0
NetServerMaxTickRate=60
LanServerMaxTickRate=60
ConnectionTimeout=45.0

[Engine.GameReplicationInfo]
ServerName=-=[Catalyst's Server]=-
ShortName=Cat
AdminName=Catalyst
AdminEmail=
Region=0
MOTDLine1=
MOTDLine2=
MOTDLine3=
MOTDLine4=

[IpDrv.TcpipConnection]
SimPacketLoss=0
SimLatency=0

[IpServer.UdpServerQuery]
GameName=ut

[IpDrv.UdpBeacon]
DoBeacon=True
BeaconTime=0.50
BeaconTimeout=5.0
BeaconProduct=ut

[SoftDrv.SoftwareRenderDevice]
Translucency=True
VolumetricLighting=True
ShinySurfaces=False
Coronas=False
HighDetailActors=False
HighResTextureSmooth=True
LowResTextureSmooth=False
FastTranslucency=True

[GlideDrv.GlideRenderDevice]
Translucency=True
VolumetricLighting=True
ShinySurfaces=True
Coronas=True
HighDetailActors=True
DetailBias=-1.500000
RefreshRate=60Hz
DetailTextures=True
FastUglyRefresh=False
ScreenSmoothing=True
Resolution=Default

[MetalDrv.MetalRenderDevice]
Translucency=True
VolumetricLighting=True
ShinySurfaces=True
Coronas=True
HighDetailActors=True
DetailTextures=False

[OpenGLDrv.OpenGLRenderDevice]
NoAATiles=True
NumAASamples=4
UseAA=False
MaskedTextureHack=True
SmoothMaskedTextures=False
FrameRateLimit=100
SwapInterval=-1
UseVertexProgram=False
UseMultiDrawArrays=False
DetailClipping=False
DetailMax=2
RefreshRate=0
MaxAnisotropy=16
Use16BitTextures=False
UseAlphaPalette=False
UseTrilinear=True
UsePrecache=False
ShareLists=False
UsePalette=False
UseMultiTexture=True
OneXBlending=False
GammaCorrectScreenshots=False
GammaOffsetBlue=0.000000
GammaOffsetGreen=0.000000
GammaOffsetRed=0.000000
GammaOffset=0.000000
LODBias=0.000000
DetailTextures=True
DescFlags=1
Description=
HighDetailActors=True
Coronas=True
ShinySurfaces=True
VolumetricLighting=True
SmoothMasking=True
ColorCorrectionMode=UseFramebuffer
ContextType=AutoDetect
UseLightmapAtlas=True
UseShaderGamma=False
UseStaticGeometry=False
UseDrawGouraud469=True
ShaderAlphaHUD=False
ForceNoSmooth=False
UseHDTextures=True
AlwaysMipmap=False

[D3DDrv.D3DRenderDevice]
Translucency=True
VolumetricLighting=False
ShinySurfaces=True
Coronas=True
HighDetailActors=True
UseMipmapping=True
UseTrilinear=False
UseMultitexture=True
UsePageFlipping=True
UsePalettes=True
UseFullscreen=True
UseGammaCorrection=True
DetailTextures=False
Use3dfx=False
UseTripleBuffering=True
UsePrecache=True
Use32BitTextures=False
DescFlags=1
dwDeviceId=9352
dwVendorId=4318
Use32BitZBuffer=False
UseVertexFog=False
UseAGPTextures=False
UseVideoMemoryVB=False
UseVSync=False
Description=NVIDIA GeForce RTX 3070

[SglDrv.SglRenderDevice]
Translucency=True
VolumetricLighting=False
ShinySurfaces=False
Coronas=True
HighDetailActors=False
ColorDepth=16
DetailTextures=False
FastUglyRefresh=False
TextureDetailBias=Near
VertexLighting=False

[Editor.EditorEngine]
UseSound=True
CacheSizeMegs=6
GridEnabled=True
SnapVertices=False
SnapDistance=10.000000
GridSize=(X=16.000000,Y=16.000000,Z=16.000000)
RotGridEnabled=True
RotGridSize=(Pitch=128,Yaw=128,Roll=128)
GameCommandLine=-log
FovAngleDegrees=90.000000
GodMode=True
AutoSave=True
AutoSaveTimeMinutes=3
AutoSaveIndex=7
C_WorldBox=(R=0,G=0,B=107,A=0)
C_GroundPlane=(R=0,G=0,B=63,A=0)
C_GroundHighlight=(R=0,G=0,B=127,A=0)
C_BrushWire=(R=255,G=63,B=63,A=0)
C_Pivot=(R=0,G=255,B=0,A=0)
C_Select=(R=0,G=0,B=127,A=0)
C_AddWire=(R=127,G=127,B=255,A=0)
C_SubtractWire=(R=255,G=192,B=63,A=0)
C_GreyWire=(R=163,G=163,B=163,A=0)
C_Invalid=(R=163,G=163,B=163,A=0)
C_ActorWire=(R=127,G=63,B=0,A=0)
C_ActorHiWire=(R=255,G=127,B=0,A=0)
C_White=(R=255,G=255,B=255,A=0)
C_SemiSolidWire=(R=127,G=255,B=0,A=0)
C_NonSolidWire=(R=63,G=192,B=32,A=0)
C_WireGridAxis=(R=119,G=119,B=119,A=0)
C_ActorArrow=(R=163,G=0,B=0,A=0)
C_ScaleBox=(R=151,G=67,B=11,A=0)
C_ScaleBoxHi=(R=223,G=149,B=157,A=0)
C_Mover=(R=255,G=0,B=255,A=0)
C_OrthoBackground=(R=163,G=163,B=163,A=0)
C_Current=(R=0,G=0,B=0,A=0)
C_BrushVertex=(R=0,G=0,B=0,A=0)
C_BrushSnap=(R=0,G=0,B=0,A=0)
C_Black=(R=0,G=0,B=0,A=0)
C_Mask=(R=0,G=0,B=0,A=0)
C_WireBackground=(R=0,G=0,B=0,A=0)
C_ZoneWire=(R=0,G=0,B=0,A=0)
DynamicActorRecompilation=False
WarnForActorRecompilation=False
AffectRegion=False
TextureLock=False
SelectionLock=False
GameRenderDevice=None
AudioDevice=None
Console=None
NetworkDevice=None
Language=None
MinClientVersion=0
MaxCacheItems=4096
MD5Enable=False
MD5AutoUpdate=False
MD5UpdateURL=
MD5Version=0
MD5LastUpdateCheck=0
EditPackages=Core
EditPackages=Engine
EditPackages=Editor
;EditPackages=UWindow
EditPackages=Fire
EditPackages=IpDrv
EditPackages=Extension
;EditPackages=UWeb
;EditPackages=UBrowser
;EditPackages=DeusExUI
;EditPackages=ConSys
;EditPackages=DeusExConversations
;EditPackages=DeusExSounds
;EditPackages=DeusExItems
;EditPackages=DeusExDeco
;EditPackages=DeusExCharacters
;EditPackages=DeusEx
;EditPackages=ConSys
EditPackages=DavesBrushBuilders
EditPackages=FrameBuilder
EditPackages=RahnemBrushBuilders
EditPackages=ExtendedBuilders
EditPackages=TarquinBrushBuilders
EditPackages=UnrealEdEx
;EditPackages=CaroneElevatorSet
EditPackages=TarquinExtrudeBuilder

[WindowPositions]
GameLog=(X=0,Y=0,XL=512,YL=384)
ConfigPageRenderer=(X=5,Y=96,XL=516,YL=280)
ConfigPageDetail=(X=5,Y=96,XL=516,YL=280)
ConfigPageFirstTime=(X=5,Y=96,XL=516,YL=280)
WizardDialog=(X=1015,Y=471,XL=530,YL=436)
ConfigPageDriver=(X=5,Y=96,XL=516,YL=280)
Find/Replace=(X=451,Y=287,XL=458,YL=193)
VFToolbar=(X=927,Y=388,XL=429,YL=24)
PictureButton=(X=795,Y=701,XL=22,YL=20)
Sound Browser=(X=516,Y=259,XL=636,YL=410)
Music Browser=(X=516,Y=259,XL=636,YL=410)
Group Browser=(X=516,Y=259,XL=636,YL=410)
Master Browser=(X=508,Y=185,XL=652,YL=492)
Actor Browser=(X=516,Y=259,XL=636,YL=410)
Texture Browser=(X=516,Y=259,XL=636,YL=410)
Mesh Browser=(X=516,Y=259,XL=636,YL=410)
Scale Lights=(X=534,Y=333,XL=291,YL=102)
Progress=(X=455,Y=341,XL=449,YL=85)
Search for Actors=(X=427,Y=244,XL=506,YL=280)
Replace Textures=(X=418,Y=223,XL=524,YL=322)
ConfigPageSafeMode=(X=5,Y=96,XL=516,YL=280)
EditorLog=(X=604,Y=67,XL=652,YL=384)
Preferences=(X=88,Y=87,XL=498,YL=512)
MdiFrameBottom=(X=117,Y=695,XL=1243,YL=32)
MdiFrameLeft=(X=0,Y=75,XL=117,YL=652)
MdiFrameTop=(X=0,Y=43,XL=1360,YL=32)
EditorToolbar=(X=0,Y=75,XL=117,YL=652)
BottomBar=(X=117,Y=695,XL=1243,YL=32)
TopBar=(X=0,Y=43,XL=1360,YL=32)
U2Viewport0=(X=117,Y=75,XL=807,YL=310)
U2Viewport1=(X=924,Y=75,XL=435,YL=310)
U2Viewport2=(X=117,Y=385,XL=807,YL=310)
U2Viewport3=(X=924,Y=385,XL=435,YL=310)
CodeFrame=(X=0,Y=0,XL=640,YL=480)
EditorFrame=(X=-32000,Y=-32000,XL=160,YL=24)
ViewDefProps=(X=220,Y=220,XL=512,YL=512)
ViewActorText=(X=220,Y=216,XL=512,YL=512)
MeshProperties=(X=242,Y=242,XL=512,YL=512)
LevelProperties=(X=264,Y=264,XL=512,YL=512)
Preferences.Split=241
ActorProperties=(X=787,Y=136,XL=512,YL=512)
2D Shape Editor=(X=0,Y=701,XL=1360,YL=27)
Extrude=(X=1168,Y=640,XL=224,YL=98)
Revolve=(X=1167,Y=632,XL=225,YL=114)
ClassProperties=(X=290,Y=144,XL=512,YL=512)
New Texture=(X=1097,Y=598,XL=366,YL=183)
SelectGroups=(X=0,Y=0,XL=640,YL=480)
ClassProperties.Split=177
Viewport Config=(X=485,Y=321,XL=389,YL=126)
ActorProperties.Split=186
Brush Builder=(X=277,Y=260,XL=349,YL=284)
Add Special=(X=511,Y=269,XL=338,YL=230)

[Botpack.TDMmaplist]

[Engine.StatLog]
LocalBatcherURL=../NetGamesUSA.com/ngStats/ngStatsUT.exe
LocalBatcherParams=
LocalStatsURL=../NetGamesUSA.com/ngStats/html/ngStats_Main.html
WorldBatcherURL=../NetGamesUSA.com/ngWorldStats/bin/ngWorldStats.exe
WorldBatcherParams=-d ../NetGamesUSA.com/ngWorldStats/logs -g UT
WorldStatsURL=http://www.netgamesusa.com
LocalLogDir=../Logs
WorldLogDir=../NetGamesUSA.com/ngWorldStats/logs
bWorldBatcherError=True
bLogTypingEvents=False

[D3D9Drv.D3D9RenderDevice]
DescFlags=1

[XOpenGLDrv.XOpenGLRenderDevice]
UsePersistentBuffers=False
UseBindlessTextures=True
UseBindlessLightmaps=True
UseShaderDrawParameters=True
UseLightmapAtlas=True
MaxBindlessTextures=0
Description=NVIDIA GeForce GT 640/PCIe/SSE2
NoDrawSimple=False
NoDrawTile=False
NoDrawGouraudList=False
NoDrawGouraud=False
NoDrawComplexSurface=False
NoBuffering=False
UseOpenGLDebug=False
UseHWClipping=False
UseHWLighting=False
GenerateMipMaps=False
UseBufferInvalidation=False
NoAATiles=True
DetailTextures=True
MacroTextures=True
BumpMaps=True
ParallaxVersion=None
GammaCorrectScreenshots=True
UseAA=False
UseTrilinear=True
UsePrecache=False
AlwaysMipmap=False
ShareLists=True
NoFiltering=False
HighDetailActors=True
Coronas=True
ShinySurfaces=True
VolumetricLighting=True
SimulateMultiPass=False
MaxAnisotropy=4.000000
LODBias=0.000000
GammaOffsetScreenshots=0.700000
DebugLevel=2
NumAASamples=4
RefreshRate=0
DescFlags=1
UseVSync=Adaptive
OpenGLVersion=Core
UseSRGBTextures=False
GammaMultiplierUED=1.000000
GammaMultiplier=1.000000
DetailMax=2

[Engine.Console]
HistoryTop=0
HistoryBot=0
HistoryCur=0
History[0]=
History[1]=
History[2]=
History[3]=
History[4]=
History[5]=
History[6]=
History[7]=
History[8]=
History[9]=
History[10]=
History[11]=
History[12]=
History[13]=
History[14]=
History[15]=

